---
- name: playing task in node1
  vars:
          firewall_pkg: firewalld
          firewall_svc: firewalld
          web_pkg: httpd
          web_svc: httpd
          ssl_pkg: mod_ssl
          httpdconf_src: files/httpd.conf
          httpdconf_dest: /etc/httpd/conf/httpd.conf
          htaccess_src: files/.htaccess
          secrets_dir: /etc/httpd/secrets
          secrets_src: files/htpasswd
          secrets_dest: "{{ secrets_dir }}/htpasswd"
          web_root: /var/www/html
  hosts: node2
  tasks:
          - name: installing latest versions of firewalld, httpd, mod_ssl
            yum:
                    name:
                            - "{{ firewall_pkg }}"
                            - "{{ web_pkg }}"
                            - "{{ ssl_pkg }}"
                    state: latest

          - name: copying
            copy:
                    src: "{{ httpdconf_src }}"
                    dest: "{{ httpdconf_dest }}"
                    owner: root
                    group: root
                    mode: 0644

          - name: creating httpd secret directory
            file:
                    path: "{{ secrets_dir }}"
                    state: directory
                    owner: apache
                    group: apache
                    mode: 0500

          - name: copying secrets file
            copy:
                    src: "{{ secrets_src }}"
                    dest: "{{ secrets_dest }}"
                    owner: apache
                    group: apache
                    mode: 0400

          - name: copying .htacces
            copy:
                    src: "{{ htaccess_src }}"
                    dest: "{{ web_root }}/.htaccess"
                    owner: apache
                    group: apache
                    mode: 0400

          - name: copying index.html
            copy:
                    content: "{{ ansible_hostname }}({{ ansible_default_ipv4.address }}) has been customized by Ansible"
                    dest: "{{ web_root }}/index.html"

          - name: enabling firewall service
            service:
                    name: firewalld
                    state: restarted
                    enabled: True

          - name: allowing httpd on firewalld
            firewalld:
                    service: https
                    permanent: True
                    immediate: True
                    state: enabled

          - name: enabling httpd service
            service:
                    name: "{{ web_svc }}"
                    state: restarted
                    enabled: True

- name: tasks for localhost
  hosts: localhost
  become: False
  vars:
          web_user: guest
  vars_files:
          - vars/secret.yml
  tasks:
          - name: requesting content from server b
            uri:
                    url: https://node2.lw.example.com
                    validate_certs: no
                    force_basic_auth: yes
                    url_username: "{{ web_user }}"
                    url_password: "{{ web_pass }}"
                    return_content: yes
                    status_code: 200
            register: task_results

          - debug: var=task_results.content



